on: [push]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish packages/test-action
      - run: npm publish packages/tsconfig
        env:
          NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}